version: '3.2'
services:
  rabbitmq_server:
    image: rabbitmq:3.7.7-management-alpine
    hostname: unicorn
    
  rabbitmq_publisher:
    build:
      context: .
      dockerfile: dockerfile-publisher
    image: unicorn-publisher:v1
    depends_on:
      - rabbitmq_server
    tty: true
    ports: 
      - "3000:3000"

  rabbitmq_consumer:
    build:
      context: .
      dockerfile: dockerfile-consumer
    image: unicorn-consumer:v1
    depends_on:
      - rabbitmq_server
      - database
    tty: true
  
  database:
    build:
      context: .
      dockerfile: dockerfile-database
    image: unicorn-database:v1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: unicorn_manager
      
  tester:
    build:
      context: .
      dockerfile: dockerfile-tester
    image: unicorn-tester:v1
    depends_on:
      - rabbitmq_consumer
      - rabbitmq_publisher
    tty: true