FROM node:10.7.0-alpine

COPY mnt/ /usr/local/unicorn
WORKDIR /usr/local/unicorn/tester
RUN apk add mysql-client && apk add nano && npm install && npm install --global mocha && cd ../consumer && npm install && cd ../publisher && npm install
CMD ["/bin/sh"]
